speced/respec-web-services

.gitignore
app.js
package.json
routes/caniuse/index.js
routes/caniuse/update.js

Mostly copy paste from xref API.
Added github webhook update endpoint also
Also, not that `/caniuse` is a GET endpoint - so we'll be passing query params like:
``` HTTP
GET /caniuse?feature=payment-request&versions=2&browsers=chrome,firefox
```

feat(caniuse): add caniuse API endpoints

---

.gitignore
package.json
routes/caniuse/index.js

- Return 404 status if feature file not found, instead of empty object with 200 status
- cache 200 status results for 24h

Update respec-caniuse-route dependency and make related changes

---

app.js
routes/xref/meta.js

``` http
GET /xref/meta
GET /xref/meta?fields=types,allTypes,specs,terms
```
``` typescript
{
types: {
idl: string[],
concept: string[],
},
specs: {
[spec: string]: {
url: string, 
shortname: string,
title: string,
}
},
terms: string[],
}
```
Depends upon: https://github.com/sidvishnoi/respec-xref-route/pull/34

feat(xref/meta): add route to expose metadata

---

static/xref/index.html

Closes #35
Concerned about the [Constructor Caveat](https://github.com/ungap/custom-elements-builtin#constructor-caveat). Please test it works in Safari.

fix(xref/ui): add built-in customElements polyfill

---

app.js
routes/xref/meta.js

Also added parameterized routes (`/xref/meta/version`, `/xref/meta/types` etc.) for fine-tuned response (can fine-tune cache-control on `/xref/meta/version` without affecting others, while keeping it in same "parent route")... and also as they're easier to write.
https://github.com/w3c/respec/pull/2473 depends on this.

feat(xref/meta): add cache version

---

app.js
routes/xref/index.js

It looks like this:
```
Listening on port 8000!
2019-08-19T09:55:15.809Z | ::1 | POST 200 /xref/ | - | 155 | 20.678 ms | -
2019-08-19T09:55:19.248Z | ::1 | POST 200 /xref/ | - | 251 | 1.585 ms | {"errors":2,"queries":3}
```

 feat(xref): log error counts

---

app.js
utils/logging.js

removes  following patterns from logs:
- automated tests: `localhost:9876/*`
- pre-flight requests to xref search: `OPTIONS 204 /xref`

 feat(logging): reduce noise in logs

---

package-lock.json
package.json
routes/github/commits.js

* rename required query param "since" to "from"
* add new query param "to"
* update respec-github-api to 1.3.0 (Changelog [v1.2.0...v1.3.0](https://github.com/sidvishnoi/respec-github-apis/compare/v1.2.0...v1.3.0))

enhancement(github/commits): get commits in range

---

.env.sample
.gitignore
app.js
package-lock.json
package.json

Better than fiddling with env variables in pm2 config file and bashrc

chore: use dotenv package to read env vars

---

routes/respec/size.js

Dashboard borked as we got entries like this while parsing newline delimited JSON:
```
{"sha": "49759ff", "time": 1590125810, "size": 295042, "gzipSize": 93329 }
{"sha": "a84344f", "time": 1590141883, "size": 295042, "gzipSize": 93329 }
{"sha":"a48a66dfb5","time":1590496824,"size":294849,"gzipSize":93369}{"sha":"9c43e5d9c5","time":1590506844,"size":294847,"gzipSize":93366}{"sha":"31b41406eb","time":1590606816,"size":294847,"gzipSize":93366}
```

fix(respec/size): add new line while appending entry

---

static/xref/.prettierrc
static/xref/script.js

Closes https://github.com/sidvishnoi/respec-xref-route/issues/63
Already supported in w3c/respec and sidvishnoi/respec-xref-route

fix(xref-ui): how-to-cite element-attr without forContext

---

routes/w3c/group.js

- `GET /w3c/groups` returns more information (instead of just group -> id)
- Note that first request to this URL will be slow, unless different group results are already cached.
- The return type is now an array instead of an object all groups
- Removed `description` field, as it was unused
- Improved type definitions

feat(w3c/groups): get detailed information on group list

---

routes/respec/size.js
static/dashboard/index.html
static/dashboard/size-chart.js

as we now use brotli instead of gzip only and "transfer" is more generic than "gzip" or "brotli"
Also see: https://github.com/w3c/respec/pull/3008
I'll update past data on server manually.

fix(respec/size): use xferSize instead of gzipSize

---

routes/w3c/group.js

Found a nice optimization when investigating. See https://github.com/marcoscaceres/respec.org/issues/100#issuecomment-660187893

perf(w3c/groups): fetch all groups in single request

---

routes/w3c/groups.json

Shortname is `secondscreen` in W3C, e.g. https://www.w3.org/groups/wg/secondscreen
(Second Screen WG specs do not yet use this label, so change shouldn't break anything)

Rename Second Screen WG

---

routes/w3c/group.js
routes/w3c/groups.json
routes/w3c/index.js

See https://github.com/marcoscaceres/respec.org/issues/114#issuecomment-694108975
```http
GET 200 /w3c/groups/webapps     # no clash, return 
GET 409 /w3c/groups/wot         # multiple groups with same shortname
GET 200 /w3c/groups/wot/wg      # okay
GET 200 /w3c/groups/webapps/wg  # for consistency
```

feat(w3c/groups): allow specifying group type

---

routes/w3c/group.js
scripts/update-w3c-groups-list.js
views/w3c/groups.js

#116 added support for lots of groups, so fetching all details on `GET /w3c/groups` will be slow as :turtle:.
As we're already collecting shortnames from W3C API, we can save some more details and show them on `/groups/`. 
TODO (followup): Show group-type-qualified name in UI (show `wot/wg` in shortname instead of `wot`).

perf(w3c/groups): use preloaded basic details

---

static/docs/src.html

https://github.com/w3c/respec/issues/3178 says:
> Duplicate ID title. There are 2 instances of id="title" on same page. One for h1 id="title" class="title" and another one for section id="title"
I'll edit wiki (page title and its references) right before uploading this on server.

fix(docs): fix duplicate id

---

routes/docs/update.js

With https://github.com/w3c/spec-generator/pull/355, we can now know if there were processing errors and avoid overwriting good `/docs/` with one with errors.

fix(docs): avoid overwrite in case of processing errors

---

routes/docs/update.js

spec-generator no longer has colors in error output.

chore(docs): avoid stripping ansi colors in error message

---

static/docs/src.html

`format: "markdown"` interfered with `data-include-format="markdown"`, causing an error in console during infoString parsing. This combined with https://github.com/marcoscaceres/respec.org/pull/127 prevent docs from updating..

fix(docs): processing error due to markdown config

---

routes/w3c/group.js

Closes https://github.com/marcoscaceres/respec.org/issues/135

fix(w3c/groups): don't use deprecated res.redirect signature

---

utils/logging.js

**Before:** `GET 200 /github/w3c/repo/issues?issues=1%2C2%2C3%2C4%2C5%2C6%2C10%2C1220&path=%0Ahello%0Aworld`
**After :** `GET 200 /github/w3c/repo/issues?issues=1,2,3,4,5,6,10,1220&path=%0Ahello%0Aworld`
Such URLs can be created in ReSpec as:
```js
const url = new URL("/github/w3c/repo/issues", "http://localhost:8000/");
// real case
url.searchParams.set("issues", [1,2,3,4,5,6,10,1220].join(","));
// edge case or bad actor trying to ruin pretty our logs
url.searchParams.set("path", `
hello
world`);
```

feat(utils/logging): make URL params cleaner

---

routes/docs/update.js

Another regression from https://github.com/marcoscaceres/respec.org/pull/144
There are no more uses of `__dirname`, so this should be last.

fix(docs/update): write generated doc to correct location

---

package-lock.json
package.json
routes/caniuse/index.js
routes/caniuse/lib/README.md
routes/caniuse/lib/constants.ts
routes/caniuse/lib/index.ts
routes/caniuse/lib/scraper.ts
routes/caniuse/update.js
scripts/update-data-sources.js
utils/sh.ts

1. Brings https://github.com/sidvishnoi/respec-caniuse-route into this repo. I've chosen `routes/caniuse/lib` as the destination.
```diff
- import { createResponseBody } from "respec-caniuse-route";
+ import { createResponseBody } from "./lib/index.js";
```
2. Added a `sh` utility, which respec-caniuse-route/scraper and others can use consistently. I've used this it in [spec-prod](https://github.com/w3c/spec-prod/blob/215ce79becbf395ec938aa35a3d44de119fcf58e/src/utils.js#L82), so it's "well tested".
```diff
- const args = shouldClone
-   ? ['clone', 'https://github.com/Fyrd/caniuse.git', 'caniuse-raw']
-   : ['pull', 'origin', 'master'];
- const cwd = shouldClone ? path.resolve(DATA_DIR) : dataDir;
- return new Promise<boolean>((resolve, reject) => {
-   const git = spawn('git', args, { …
```

refactor(route/caniuse): merge respec-caniuse-route to main

---

routes/caniuse/lib/scraper.ts
routes/xref/lib/scraper.ts

> Premature optimization is the root of all evil.
Regression from https://github.com/marcoscaceres/respec.org/pull/146, https://github.com/marcoscaceres/respec.org/pull/148 causing merge errors on pull.

fix(xref/scraper, caniuse/scraper): don't shallow clone

---

package-lock.json
package.json
utils/background-task-queue.ts

`Error` isn't serialized across `postMessage`.

fix(utils/background-task-queue): serialize/deserialize errors

---

scripts/regenerate-docs.js
scripts/update-data-sources.js
scripts/update-w3c-groups-list.js

Closes https://github.com/marcoscaceres/respec.org/issues/123
Closes https://github.com/marcoscaceres/respec.org/issues/124
Getting started now is:
1. Clone repo, npm install
2. Copy `.env.sample` to `.env`
1. Set `DATA_DIR`  to `pwd` + `"data"` (or some path outside repo)
2. Set `W3C_API_KEY` to `"IGNORE"` (or if you have key, use it. Without a correct key, `/w3c/*` pages will error when viewed).
3. Let everything else stay same.
3. `npm run update-data-sources`
4. (Optional) `node scripts/regenerate-docs.js`

chore: simplify update-data-sources script

---

routes/caniuse/lib/scraper.ts

Somehow, `Intl.Collator` gives better results than our implementation :smile: 
```diff
- ["14", "13.1", "13", "12.1", "12", "11.1", "11", "10.1", "10", "9.1", "9", "8", "7.1", "7", "6.1", "6", "5.1", "5", "4", "3.2", "3.1", "TP"]
+ ["TP", "14", "13.1", "13", "12.1", "12", "11.1", "11", "10.1", "10", "9.1", "9", "8", "7.1", "7", "6.1", "6", "5.1", "5", "4", "3.2", "3.1"]
```
```diff
- ["81", "4.4.3-4.4.4", "4.4", "4.1", "4.2-4.3", "4", "3", "2.3", "2.2", "2.1"] 
+ ["81", "4.4.3-4.4.4", "4.4", "4.2-4.3", "4.1", "4", "3", "2.3", "2.2", "2.1"]
```

fix(caniuse/scraper): fix browser version sorting

---

routes/github/contributors.js
utils/disk-cache.ts
utils/mem-cache.ts

Added in `DiskCache` which persists caching across app restarts, which is useful with expensive operations. It'll allow us to restart server often without losing the cached data. It's a database, but without the hassle of a database.
This filesystem-backed cache is used internally in [respec-github-apis](https://github.com/sidvishnoi/respec-github-apis) as [`TTLCache`](https://github.com/sidvishnoi/respec-github-apis/blob/main/utils/cache.ts). I'm bringing it here in this PR as a step to move respec-github-apis into this repo, similar to https://github.com/marcoscaceres/respec.org/pull/146 and https://github.com/marcoscaceres/respec.org/pull/148.
As a demonstration, I converted `/github/org/repo/contributors` endpoint to use the disk cache:
|                    | Before …

feat(utils/disk-cache): add filesystem-backed persistent cache

---

routes/caniuse/index.ts
routes/github/index.ts
routes/w3c/index.ts
routes/xref/index.ts

..as these are simple-request endpoints that don't require pre-flight requests.
Also set maxAge for /xref pre-flight request (Closes https://github.com/marcoscaceres/respec.org/issues/150)

refactor(*): remove unnecessary OPTIONS requests

---

static/specref/index.html
static/specref/script.js
static/specref/style.css

Moved from w3c/respec along with some improvements.
Demo: https://raw.githack.com/marcoscaceres/respec.org/specref-ui/static/specref/index.html
<details>
<summary>Potential size changes in ReSpec</summary>
| File             | Before |  After |  Diff |
| ---------------- | -----: | -----: | ----: |
| respec-w3c.js    | 308252 | 304014 | -4238 |
| respec-w3c.js.br |  84815 |  83563 | -1252 |
| respec-w3c.js.gz |  98219 |  96754 | -1465 |
</details>

feat(specref-ui): add a UI for Specref search

---

routes/xref/lib/scraper.ts

Also reduce `xref.json` size from `9771157` to `9512071` (minus 259086 bytes, or ~250KiB)

fix(xref/scraper): ensure data by term is unique

---

app.ts

Fixes following error when accessing `/w3c/groups` (regression from https://github.com/marcoscaceres/respec.org/pull/176):
```
Error: Failed to lookup view "w3c/groups.js" in views directory "/path/to/respec.org/views"
at Function.render (/path/to/respec.org/node_modules/express/lib/application.js:580:17)
at ServerResponse.render (/path/to/respec.org/node_modules/express/lib/response.js:1012:7)
at route (file:///path/to/respec.org/routes/w3c/group.ts:46:18)
at Layer.handle [as handle_request] (/path/to/respec.org/node_modules/express/lib/router/layer.js:95:5)
at next (/path/to/respec.org/node_modules/express/lib/router/route.js:137:13)
at cors (/path/to/respec.org/node_modules/cors/lib/index.js:188:7)
at /path/to/respec.org/node_modules/cors/lib/index.js:224:17
at originCallback …
```

fix(app): load views from build directory

---

app.ts
routes/well-known/index.ts
routes/well-known/pay.ts

In respec, we can now use `$respec.org` as payment pointer.

feat(.well-known/pay): add own payment pointer with rev sharing

---

routes/xref/lib/constants.ts

Fixes #203 
@marcoscaceres With no further changes, constants can now be referenced  in ReSpec as `{{HTMLMediaElement/HAVE_METADATA}}` (though they've no particular data-type). Do we want a different syntax (mainly to disambiguate `data-type` in case it's needed; maybe `{{HTMLMediaElement::HAVE_METADATA}}`)?

feat(xref): support IDL constants

---

routes/xref/lib/scraper.ts

Fixes https://github.com/w3c/respec-web-services/issues/202
allows searching for abstract-op terms by treating them same as `dfn` or `_CONCEPT_`

fix(xref/scraper): rename abstract-op to dfn

---

static/docs/src.html

Adds `latestVersion` to docs, as a W3C only option.

docs(src): add latestVersion

---

routes/caniuse/lib/scraper.ts

fix(caniuse/scraper): correctly process multi-version entries

---

static/xref/script.js

fix(xref/ui): add SyntaxError to exception exceptions

---

routes/w3c/group.ts
scripts/update-w3c-groups-list.ts
views/w3c/groups.ts

This matches api.w3.org and www.w3.org/groups
Fixes https://github.com/w3c/respec-web-services/issues/243

fix(w3c/groups): use 'other' instead of 'misc', support AB

---

static/docs/src.html

Use the w3c permissive license (default).

fix(docs): use default license

---

routes/w3c/group.ts

The W3C now has "special" URLs for the wgURI. 
then I can get rid of:
https://github.com/w3c/respec/pull/3848/files#diff-13273a4f4852f048daddcee7ee5d06a808e5ba8edf4e7c6a3472c5176faed45c

feat(w3c/groups): add wgURI to JSON response

---

views/w3c/groups.ts

Showing the number is confusing, as you can't actually use it for configuration.

docs(/w3c/groups/): don't show group number

---

static/docs/src.html

It's accidentally listed twice (see 13.5).

docs: remove wgPatentPolicy, as it is internal

---

routes/caniuse/feature.ts
routes/caniuse/lib/index.ts

Returns a 404 if /caniuse/whatever is not a file on the server, but without exposing the lstat details in the response. 
We then show the right error on the front-end. 
I also made the fails a bit more aggressive by not returning `null`... if it fails, we should really be returning 500s and dealing with that on the client.

fix(/caniuse/:feature): return 404 if feature not on file

---

routes/caniuse/feature.ts

For when it's always been supported, it was retuning "u".

fix(/caniuse/:feature): incorrect result

---

routes/caniuse/index.ts
utils/logging.ts

As suggested in https://github.com/w3c/respec-web-services/pull/272#discussion_r825816749
1. a `deprecated` field is added to filter logs
2. the status in logs is underlined for deprecated routes

chore(/caniuse): monitor usage of deprecated route

---

routes/w3c/group.ts

Fixes https://github.com/w3c/respec-web-services/issues/326

fix(w3c/groups): better hint if multiple groups with same shortname

---

@types/webref.d.ts
routes/xref/lib/scraper.ts
routes/xref/lib/search.ts
tests/routes/xref/lib/data-by-term.js
tests/routes/xref/lib/search.test.js
tests/routes/xref/lib/utils.test.js

See https://github.com/w3c/respec/issues/4522#issuecomment-1933574282 for context

feat(/xref): expose `htmlProse` field from webref

---

static/docs/src.html

closes #404 
Checked that it is indeed not in the codebase

fix(docs/src): add prEnd, remove lcEnd

---

static/xref/script.js

For specs like "The <model> element", which otherwise end up as actual HTML tags 😬

fix(xref:ui): escape HTML in spec title

---

static/xref/script.js

Enum values need to be wrapped in double quotes as described in: https://respec.org/docs/#examples-0
The "How to cite" column listed them without double quotes. This update adds the double quotes when needed.
Note: I haven't managed to run the service locally, so haven't tested the update. I'm happy for anyone to take over and fix this differently ;)

fix(/xref:ui): wrap enum values in quotes in "How to cite"

---

utils/disk-cache.ts

Missed in https://github.com/speced/respec-web-services/pull/440 when testing https://github.com/speced/respec-web-services/pull/435

fix(utils/DiskCache): better secure path used as cache key

---

routes/github/commits.ts
routes/github/lib/commits.ts

Part of https://github.com/speced/respec/issues/4754
Adds an optional path parameter to the GH commits interface.
Usage allows multiple specs hosted in a monorepo to specific either a folder or a file/folder and only return commits against that file.
Usage will require a corresponding change to gh-changelog in respec to enable this ability

feat(/github/commits): support filter by path

---

routes/respec/builds/update.ts
routes/respec/index.ts
scripts/update-data-sources.ts

- Latest respec builds to be available under `/respec/builds`, e.g. https://respec.org/respec/builds/respec-w3c.js
- Served with a `max-age=10min`
- Uses webhook event from respec repo (scope: release, action=released) to trigger pull from npm. We create releases in respec manually.

feat(/respec/builds): host latest release from npm

---

routes/respec/index.ts

We set these policies at top-level `app` via `helmet`, which doesn't have a way to undo these headers. So, we remove these headers at route level.

fix(/respec/builds): remove CSP/COOP/CORP
