.gitignore
index.js
package.json

Hehe. This one was easy. 8 lines :P

feat(index.js): add xref API

---

index.js
routes/xref/index.js

Part of https://github.com/marcoscaceres/respec.org/pull/3
Separating PR just to keep commits localized.

refactor(/xref): Move to routes directory

---

index.js
package.json

Closes https://github.com/sidvishnoi/respec-xref-route/issues/8
We could enable cors on entire app, or on specific route as needed.

feat(/xref): enable cors

---

package.json

chore(package): use xref route v4.0.0

---

app.js
package-lock.json
package.json

sec: add hamlet to control security aspects

---

static/xref/index.html
static/xref/script.js

feat(xref-ui): auto-suggest terms

---

static/xref/script.js

fix(script.js): Remove spaces from how to cite

---

static/xref/index.html
static/xref/script.js

Also refactored howToCite by splitting it in two... this makes it a bit easier to maintain, hopefully.

fix(xref/script): some exceptions are interfaces

---

utils/logging.js

`hostname` was something different 🤦‍♂

fix(logging): skip automated tests

---

app.js
package.json
routes/github/contributors.js

For https://github.com/w3c/respec/issues/2446
``` http
GET /github/w3c/respec/contributors
```
``` json
[
{
"name": "Marcos Cáceres",
"login": "marcoscaceres",
"contributions": 1975
},
{
"name": "Robin Berjon",
"login": "darobin",
"contributions": 862
},
...
]
```

feat(github/contributors): add endpoint for repo contributors

---

app.js
package.json
routes/github/issues.js

``` http
GET /github/w3c/payment-request/issues?issues=879,817,1200
```
``` js
// Content-Type: application/json
{
"817": {
"title": "Extensibility of PaymentResponse.complete(result)",
"state": "OPEN",
"labels": [
{
"name": "Extensibility",
"color": "1d76db"
},
{
"name": "Future Candidate Feature",
"color": "006b75"
},
// ...
]
},
"1200": null,
"879": {
// ...
}
}
```
```
// Status-Code URL | Content-Length | Response-Time
200 /github/w3c/payment-request/issues?issues=879,817 | 401 B | 493.143 ms  // cache miss
200 /github/w3c/payment-request/issues?issues=879,817 | 401 B | 0.425 ms    // cache hit
200 /github/w3c/payment-request/issues?issues=879,a,817 | 401 B | 0.438 ms  // cache hit, "a" is skipped
404 /github/bobby/tables/issues?issues=879,817 | 9 B | 457.059 ms           // repo not …
```

feat(github/issues): get issue details by issue numbers

---

package.json
routes/github/commits.js
routes/github/index.js

``` http
GET /github/w3c/payment-request/commits?since=CR
```

feat(github/commits): list commits since a ref

---

static/xref/index.html
static/xref/script.js

feat(xref-ui): share search queries via URL

---

package-lock.json
package.json
routes/github/files.js
routes/github/index.js

For https://github.com/w3c/respec/issues/1596
Depends on https://github.com/sidvishnoi/respec-github-apis/pull/3

feat(github/files): recursively list files in a repository

---

package-lock.json
package.json
routes/xref/meta.js
static/xref/script.js

For: https://github.com/w3c/respec/issues/2705

feat(xref): allow searching markup types

---

utils/logging.js

https://github.com/marcoscaceres/respec.org/commit/4d1b42d61dd353a3b57ef796a5390fc12e6f96f2#r37451546

fix(logging): fix chalk v3 update regression

---

.github/workflows/healthcheck.yml

chore(ci/healthcheck): add healthcheck cron service

---

app.js

Thanks to https://stackoverflow.com/a/50689893

fix(app): make dotenv work with pm2

---

static/dashboard/index.html
static/dashboard/size-chart.js
static/dashboard/style.css

Demo: https://respec.org/dashboard/
(Checked in this branch on server, doesn't require server restart as it's in /static)

feat(dashboard): add respec-w3c size tracker

---

package-lock.json
package.json
routes/xref/index.js
routes/xref/meta.js
routes/xref/update.js

[Release notes v7.0.0](https://github.com/sidvishnoi/respec-xref-route/releases/tag/v7.0.0)

chore(xref): update to respec-xref-route@v7.0.0

---

package-lock.json
package.json
routes/xref/meta.js
static/xref/script.js

feat(xref): support css types

---

routes/xref/index.js
static/xref/filter/index.html
static/xref/filter/script.js
static/xref/filter/style.css
static/xref/filter/worker.js

Demo: https://i.imgur.com/8hPzaJj.mp4

feat(/xref/filter): add UI to filter raw xref data

---

static/xref/script.js

fix(xref-ui): make term search case insensitive

---

routes/caniuse/update.js
routes/respec/size.js
routes/xref/update.js
utils/misc.js

refactor: add util function to get env variable

---

.github/workflows/healthcheck.yml

This is why didn't get alerts about recent outage due to SSL error (https://github.com/w3c/respec/issues/2979)

chore(healthcheck): do not exit on failed request

---

.env.sample
app.js
routes/docs/index.js
routes/docs/update.js
scripts/regenerate-docs.js

- Regenerate doc when wiki is updated by listening to a webhook event.
- Also, be able to manually update wiki if needed.

feat(docs): regenerate on wiki update

---

app.js

..until we design a pretty home page.

chore: temporarily redirect home page to /docs

---

routes/docs/update.js
routes/w3c/group.js
utils/misc.js

See https://github.com/marcoscaceres/respec.org/pull/101#discussion_r456744995

refactor: use HTTPError class

---

routes/w3c/group.js

This reverts https://github.com/marcoscaceres/respec.org/commit/f3aa60f9793db57414e542044833235faf8ac9a0 and simplifies some code.
Doing this in preparation for https://github.com/marcoscaceres/respec.org/issues/108

refactor(w3c/groups): fetch details as required

---

jsconfig.json

Codebase is not yet ready for strict mode though...

chore: add a jsconfig.json for better TS support

---

routes/w3c/group.js

Closes https://github.com/marcoscaceres/respec.org/issues/108

feat(w3c/groups): expose WG patentPolicy info 

---

routes/w3c/group.js

Minor changes to error messages..

fix(w3c/groups): improve error messages

---

routes/w3c/group.js
scripts/update-w3c-groups-list.js
views/w3c/groups.js

Closes https://github.com/w3c/respec/issues/3130

feat(w3c/groups): support BGs and IGs

---

routes/w3c/group.js
scripts/update-w3c-groups-list.js
views/w3c/groups.js

See https://github.com/w3ctag/ethical-web-principles/pull/30#issuecomment-698287932

feat(w3c/groups): support misc groups like TAG

---

routes/w3c/group.js

Closes https://github.com/marcoscaceres/respec.org/issues/121

fix(w3c/groups): reduce cache duration to 1 day

---

static/xref/index.html

fix(xref-ui): always include custom elements polyfill

---

routes/w3c/group.js

Fixes https://github.com/marcoscaceres/respec.org/issues/131

fix(w3c/groups): handle missing accept header

---

.env.sample
package-lock.json
package.json
routes/xref/index.js
routes/xref/update.js

Based on https://github.com/sidvishnoi/respec-xref-route/pull/70

feat(xref): use reffy data

---

routes/caniuse/update.js
routes/xref/update.js

chore: avoid console.log as it makes logs hard to parse

---

routes/docs/update.js

Regression from https://github.com/marcoscaceres/respec.org/pull/136

fix(docs/update): fix __dirname is not defined

---

app.js
utils/constants.ts
utils/dotenv.ts
utils/misc.js

Regression from https://github.com/marcoscaceres/respec.org/pull/144

fix: use PROJECT_ROOT constant instead of flaky __dirname

---

package-lock.json
package.json
utils/logging.ts

Fixes https://github.com/marcoscaceres/respec.org/issues/138
(Side-by-side diff recommended)

refactor(utils/logging): rewrite in TypeScript

---

routes/caniuse/lib/constants.ts
routes/caniuse/lib/index.ts
routes/caniuse/lib/scraper.ts

Closes https://github.com/marcoscaceres/respec.org/issues/149
We should update the styles in respec (partial support, behind flag are shown as same, but title are different).
Also, titles in HTML here have some room for improvement.
~And as a performance improvement, we should do the grouping in scraper (while still supporting legacy json format).~ done.
<details>
<summary>Demo: Payment Request</summary>
</details>
<details>
<summary>Demo: Manifest</summary>
</details>
<details>
<summary>Generated HTML for web-app-manifest</summary>
```html
<div class="caniuse-browser">
<button class="caniuse-cell y" title="Supported.">Chrome 91</button>
<ul>
<li class="caniuse-cell y" title="Supported.">39-90</li>
<li class="caniuse-cell n" title="Not supported by default, but can be enabled.">4-38</li> …
```

feat(caniuse): group browser versions with similar support

---

package-lock.json
package.json
routes/github/commits.js
routes/github/contributors.js
routes/github/files.js
routes/github/issues.js
routes/github/lib/README.md
routes/github/lib/commits.ts
routes/github/lib/contributors.ts
routes/github/lib/files.ts
routes/github/lib/issues.ts
routes/github/lib/users.ts
routes/github/lib/utils/graphql.ts
routes/github/lib/utils/rest.ts
routes/github/lib/utils/tokens.ts

Moving https://github.com/sidvishnoi/respec-github-apis/ into this repo, similar to #146 and #148. This would be the last merger.

refactor(route/github): merge respec-github-apis to main

---

routes/caniuse/update.js

This explains why caniuse data on server hasn't been updated for over a month..

fix(caniuse/update): set valid branch to main

---

scripts/update-w3c-groups-list.js

Regression from https://github.com/marcoscaceres/respec.org/pull/165

fix(scripts/update-w3c-groups-list): use utils/misc.js from build dir

---

routes/xref/lib/constants.ts
routes/xref/lib/scraper.ts
routes/xref/lib/search.ts
static/xref/index.html
static/xref/script.js
static/xref/style.css

Closes https://github.com/marcoscaceres/respec.org/issues/172
(Review commit by commit)

feat(xref): include dfns from snapshots also

---

app.ts
package-lock.json
package.json

refactor(app): rewrite in TypeScript

---

static/xref/index.html
static/xref/script.js
static/xref/style.css

Closes https://github.com/w3c/respec/issues/3440

feat(xref/ui): add last updated time, link to webref

---

routes/github/lib/issues.ts

fix(github/issues): reduce cache time from 12h to 6h

---

static/xref/script.js

fix(xref/ui): display timezone in last updated mark

---

routes/xref/lib/search.ts
tests/routes/xref/lib/data-by-term.js
tests/routes/xref/lib/search.test.js

Fixes https://github.com/w3c/respec-web-services/issues/216
Closes https://github.com/w3c/respec-web-services/pull/217 (supersedes)

fix(xref/search): find concepts by varying term in multiple passes

---

package-lock.json
package.json

As I always forget this on the server.

chore(.git/hooks): install and build on git pull

---

package-lock.json
package.json
routes/docs/update.ts
routes/github/lib/commits.ts
routes/github/lib/issues.ts
routes/github/lib/utils/graphql.ts
routes/github/lib/utils/rest.ts
routes/github/lib/utils/tokens.ts
routes/w3c/group.ts
routes/well-known/pay.ts
scripts/update-w3c-groups-list.ts

- Updated dependencies
- Removed `@types/node-fetch` as `node-fetch@3` includes them.
- Updated TypeScript usage to align with updates and have stricter types.

chore(deps): update dependencies

---

static/docs/src.html
static/docs/style.css

fix(docs): make logo smaller

---

static/docs/src.html

docs: include developers guide as appendix

---

routes/xref/lib/constants.ts

as discussed in https://github.com/speced/spec-dfn-contract/issues/8
See also mention in https://github.com/w3c/respec-web-services/issues/228

Add support for 'permission' dfn-type

---

routes/xref/lib/search.ts

Currently doesn't link, for example, [="web-share"=]... 
Need to start adding tests :(

fix(xref/lib/search): treat permission as concept

---

routes/caniuse/lib/constants.ts

Provide a more detailed view of the world, to complement https://github.com/w3c/respec/pull/4080

fix(caniuse/constants): update DEFAULT_BROWSERS and drop old browsers

---

scripts/update-w3c-groups-list.ts

As mentioned in https://github.com/w3c/respec-web-services/issues/315#issuecomment-1173692594, some groups were missing from our list:
Earlier:
```
Updating W3C groups list...
Processing 432 items...
Writing 432 entries to data/w3c/groups.json..
```
Now:
```bash
Updating W3C groups list...
Processing 467 items...
Writing 435 entries to data/w3c/groups.json..
```

fix(w3c/groups): include missing TF member groups

---

routes/xref/lib/constants.ts
routes/xref/lib/search.ts
routes/xref/meta.ts
static/xref/script.js

Closes https://github.com/w3c/respec-web-services/issues/331

feat(/xref): allow searching for http-header

---

routes/well-known/pay.ts

chore: comment out Marcos's payment pointer

---

routes/w3c/group.ts

Closes https://github.com/w3c/respec-web-services/issues/379
The actual error was likely transient, but our error handling was lacking.

fix(w3c/groups): handle errors better

---

routes/w3c/group.ts
scripts/update-w3c-groups-list.ts

no longer needed to access the W3C API

fix(/w3c/group): remove W3C API key as not needed

---

static/docs/src.html

Closes https://github.com/w3c/respec/issues/4396

feat(/docs): add informative-dfn, no-unused-dfns lint & `.lint-ignore`

---

package.json
pnpm-lock.yaml

chore(package.json): use pnpm in post-merge git hook

chore(deps): update dependencies, pnpm

---

.env.sample
static/dashboard/size-chart.js
static/docs/src.html

See https://github.com/w3c/respec/issues/4713

chore: update W3C org references to speced for repo migration
